# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V_BATCH_ID', models.IntegerField(default=0)),
                ('V_TASK_ID', models.CharField(blank=True, default='', max_length=20)),
                ('I_PARAMETER_ORDER', models.IntegerField(default=0)),
                ('V_PARAMETER_NAME', models.CharField(blank=True, default='', max_length=400)),
                ('V_PARAMETER_VALUE', models.CharField(blank=True, default='', max_length=400)),
            ],
            options={
                'ordering': ('V_BATCH_ID', 'V_TASK_ID', 'I_PARAMETER_ORDER'),
            },
        ),
        migrations.RenameModel(
            old_name='batchs',
            new_name='batch',
        ),
    ]
