# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchs', '0002_auto_20170226_0329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={},
        ),
    ]
