# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batchs', '0003_auto_20170226_0333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ('V_BATCH_ID',)},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ('V_BATCH_ID', 'V_TASK_ID', 'I_PARAMETER_ORDER')},
        ),
    ]
