# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20170326_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
